### ISSUE TITLE
v0.2 printer.cfg file

### ISSUE THREAD

**Issue by martingim** [stvptrsn/Printer_Stuff#2]
In the printer.cfg file or the voron 0.2. The set_position lines, 231 and 232,  can lead to crashing the printhead if you.
1. Home all axes
2. move the printhead around with the controls
3. home only Y or X

**Comment by stvptrsn** [comment]
I know this is a REALLY old issue, and I'm sorry for the extremely delayed response.  These configurations are posted as a reference per the build that I show on-stream.  I'd like to keep them updated, but the reality is I just don't have the bandwidth to do that.
