### ISSUE TITLE
spool_holder_base M5 roll-in nuts can't be used

### ISSUE THREAD

**Issue by idonasch** [stvptrsn/Printer_Stuff#3]
Roll-in nuts are no symmetrically and the 2020 rail guides need to be offset. Workaround is to use t-nuts.

**Comment by stvptrsn** [comment]
Yep, I still need to add hardware notes.  Hammerhead tnuts are required, it could very well be remixed to use roll-ins but I wanted more support against the bottom of the extrusion slots so decided to use hammerheads.
